[package]
name = "UGCValidation"
version = "1.12.14"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!*.spec.lua",
    "!*jest.config.lua",
    "!*.rbxm",
    "!AssetsForUnitTests",
]
publish = true
[dependencies.Cryo]
target = "https://github.com/roblox/cryo"
version = "^1.0"

[dependencies.Promise]
target = "https://github.com/roblox/roblox-lua-promise"
version = "^3.3.0"
[dev_dependencies.Jest]
target = "https://github.com/roblox/jest-roblox"
version = "^3.3.0"

[dev_dependencies.JestGlobals]
target = "https://github.com/roblox/jest-roblox"
version = "^3.3.0"
