[package]
name = "Jest"
version = "3.8.0"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.JestCore]
package = "JestCore"
version = "^3.8.0"
