[package]
name = "ReactSceneUnderstanding"
version = "0.5.0"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!**/*.spec.lua",
    "!**/*.bench.lua",
]
publish = true
authors = [
    "Marin Minnerly <dminnerly@roblox.com>",
    "#content-music",
]
description = "React context and hooks for SceneUnderstanding"
repository = "https://github.com/Roblox/scene-understanding-internal"
homepage = "https://roblox.github.io/scene-understanding-internal/"
documentation = "https://roblox.github.io/scene-understanding-internal/"
[dependencies.Cryo]
target = "https://github.com/roblox/cryo"
version = "^1.1.0"

[dependencies.React]
target = "https://github.com/roblox/roact-alignment"
version = "^17.0.2"

[dependencies.SceneUnderstanding]
package = "SceneUnderstanding"
version = "^0.5.0"
[dev_dependencies.InternalTestUtils]
package = "InternalTestUtils"
version = "^0.5.0"

[dev_dependencies.Jest]
target = "https://github.com/roblox/jest-roblox"
version = "^3.8.0"

[dev_dependencies.JestBenchmark]
target = "https://github.com/roblox/jest-roblox"
version = "^3.8.0"

[dev_dependencies.JestGlobals]
target = "https://github.com/roblox/jest-roblox"
version = "^3.8.0"

[dev_dependencies.ReactTestingLibrary]
target = "https://github.com/roblox/react-testing-library-lua"
version = "^12.2.2"

[dev_dependencies.ReactTestingUtils]
target = "https://github.com/roblox/react-utils"
version = "^1.2.0"

[dev_dependencies.Rhodium]
target = "https://github.com/roblox/rhodium"
version = "^0.5.0"
