[package]
name = "Foundation"
version = "1.2.3"
readme = "README.md"
content_root = "src"
files = [
    "*",
    "!*.test.lua",
    "!*.story.lua",
    "!*.bench.lua",
    "!Utility/Stories/*",
    "!Utility/benchmarks.lua",
    "!Utility/createRenderSpy.lua",
    "!*.csv",
]
publish = true
authors = [
    "Nick Winans <nwinans@roblox.com>",
    "Andrea Fletcher <afletcher@roblox.com>",
    "Rikesh Subedi <rsubedi@roblox.com>",
]
description = "Ready-to-use foundational React Luau components."
repository = "https://github.com/Roblox/foundation"
keywords = [
    "foundation",
    "react",
    "ui",
    "components",
]
homepage = "https://foundation.roblox.com"
documentation = "https://foundation.roblox.com"
[dependencies.Cryo]
version = "^1.1.0"

[dependencies.Dash]
version = "^1.0.0"

[dependencies.FoundationImages]
version = "^1.0.1"

[dependencies.Lumberyak]
package = "lumberyak"
version = "^0.1.1"

[dependencies.Otter]
version = "^1.2.1"

[dependencies.RbxDesignFoundations]
version = "= 2.0.132"

[dependencies.React]
version = "^17.0.6"

[dependencies.ReactIs]
version = "^17.0.6"

[dependencies.ReactOtter]
version = "^1.2.1"

[dependencies.ReactUtils]
version = "^1.3.1"

[dependencies.Roact]
package = "RoactCompat"
version = "^17.0.6"

[dependencies.RoactGamepad]
version = "^0.5.10"

[dependencies.SafeFlags]
version = "^0.1.0"

[dependencies.UsageTracker]
version = "^0.1"
[dev_dependencies.DocUtils]
version = "^0.1.13"

[dev_dependencies.Jest]
version = "^3.8.0"

[dev_dependencies.JestBenchmark]
version = "^3.8.0"

[dev_dependencies.JestGetType]
version = "^3.8.0"

[dev_dependencies.JestGlobals]
version = "^3.8.0"

[dev_dependencies.LuaYaml]
version = "^0.1.0"

[dev_dependencies.ReactTestingLibrary]
version = "^12.2.3"
