[package]
name = "FoundationImages"
version = "1.1.1"
readme = "README.md"
content_root = "src"
files = ["*"]
publish = true
authors = [
    "Nick Winans <nwinans@roblox.com>",
    "Andrea Fletcher <afletcher@roblox.com>",
]
description = "Source for all images used in Foundation."
repository = "https://github.com/Roblox/foundation-images"
keywords = [
    "images",
    "foundation",
    "icons",
]
homepage = "https://foundation.roblox.com/Images/"
documentation = "https://foundation.roblox.com/Images/"
