[package]
name = "JestGlobals"
version = "3.8.0"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.Expect]
package = "Expect"
version = "^3.8.0"

[dependencies.JestEnvironment]
package = "JestEnvironment"
version = "^3.8.0"

[dependencies.JestTypes]
package = "JestTypes"
version = "^3.8.0"

[dependencies.LuauPolyfill]
version = "^1"
