[package]
name = "JestTypes"
version = "3.8.0"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.LuauPolyfill]
version = "^1"

[dependencies.RegExp]
version = "^0.2.1"
