[package]
name = "JestUtil"
version = "3.8.0"
content_root = "src"
files = [
    "*",
    "!**/__tests__/**",
]
publish = true
license = "MIT"
[dependencies.ChalkLua]
version = "^0.2.0"

[dependencies.JestTypes]
package = "JestTypes"
version = "^3.8.0"

[dependencies.LuauPolyfill]
version = "^1"

[dependencies.Picomatch]
version = "^0.4.0"

[dependencies.Promise]
version = "^3.3.0"

[dependencies.RegExp]
version = "^0.2.1"

[dependencies.RobloxShared]
package = "RobloxShared"
version = "^3.8.0"
